pipeline {
    // GANTI baris label 'Ubuntu' menjadi ini:
    agent any 

    stages {
        stage('Hello') {
            steps {
                // Ini yang akan memunculkan tulisan yang Anda mau
                echo 'Hello World'
            }
        }
    }
}