pipeline {
    agent any

    stages {
        stage('Welcome') {
            steps {
                echo 'Memulai Pipeline...'
            }
        }
        stage('Hello') {
            steps {
                // Baris ini akan mencetak teks yang Anda inginkan di console
                echo 'Hello World'
            }
        }
    }
}